name: Daily Forex Notifier

on:
  schedule:
    - cron: "0 16 * * *"   # 每天 UTC 16 点（北京时间 24 点）运行
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python forex_notifier.py
